version: '3.8'

services:
  ada-aws-project:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:      
      NODE_ENV: production
